
"APPLE_SIGNIN"
{"CLIENT_ID":"com.nerdwallet","IS_ENABLED_ON_WEB",true},
"ASSETS_URL":"https://www.nerdwallet.com/cdn/apps/prod/compass","BASE_URI","/compass","BREADCRUMBS"
{"ADVISORS"
{"LABEL"
"Advisors","PARENT_SLUG"
"HOMEPAGE","URL"
""},"AUTO_LOANS"
{"LABEL"
"Auto Loans","PARENT_SLUG"
"HOMEPAGE","URL"
""},"BANKING"
{"LABEL"
"Banking","PARENT_SLUG"
"HOMEPAGE","URL"
""},"BROKERS"
{"LABEL
"Brokers","PARENT_SLUG
"HOMEPAGE","URL
""},"CREDIT_CARDS
{"LABEL
"Credit Cards","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/credit-cards"},"FINANCE
{"LABEL
"Personal Finance","PARENT_SLUG
"HOMEPAGE","URL
"/hub/category/finance"},"HOMEPAGE
{"LABEL
"Back to NerdWallet homepage","URL
"/"},"INSURANCE
{"LABEL
"Insurance","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/insurance"},"INVESTING
{"LABEL
"Investing","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/investing"},"LOANS
{"LABEL
"Loans","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/loans"},"MEDICARE
{"LABEL
"Medicare","PARENT_SLUG
"INSURANCE","URL
"/hub/category/medicare"},"MEMBER_CARDS
{"LABEL
"Cards","PARENT_SLUG
"MEMBER_HOME","URL
"/home/dashboard/cards"},"MEMBER_CASH_FLOW
{"LABEL
"Cash Flow","PARENT_SLUG
"MEMBER_HOME","URL
"/home/dashboard/cash-flow"},"MEMBER_CREDIT_SCORE
{"LABEL
"Credit Score","PARENT_SLUG
"MEMBER_HOME","URL
"/home/dashboard/credit-score"},"MEMBER_HOME
{"LABEL
"Back to My NerdWallet","URL
"/home/dashboard/home"},"MEMBER_NET_WORTH
{"LABEL
"Net Worth","PARENT_SLUG
"MEMBER_HOME","URL
"/home/dashboard/net-worth"},"MORTGAGES
{"LABEL
"Mortgages","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/mortgages"},"PERSONAL_LOANS
{"LABEL
"Personal Loans","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/personal-loans"},"SHOPPING
{"LABEL
"Shopping","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/personal-finance "},"SMALL_BUSINESS
{"LABEL
"Small Business","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/small-business"},"STUDENT_LOANS
{"LABEL
"Student Loans","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/student-loans"},"TAXES
{"LABEL
"Taxes","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/taxes"},"TRAVEL
{"LABEL
"Travel","PARENT_SLUG
"HOMEPAGE","URL
"/h/category/travel"},"UTILITIES
{"LABEL
"Utilities","PARENT_SLUG
"HOMEPAGE","URL
"/hub/category/utilities"}},"CDN_URL
"https://www.nerdwallet.com/cdn","CLIENT_ID
"compass","CONFIG_ENV
"production","ENROLL_MFA
{"ENABLED
false,"SECOND_FACTORS
{"TOTP
false}},"FEATURES_FLAGS_BASE_URL
"https://features.nerdwallet.com","FINPRO_BASE_URL
"https://www.nerdwallet.com/api","GN_SENTRY_DSN
"https://84dcf2cd2d3d44cbac84f52aad13b72e@o23637.ingest.sentry.io/4504851064881152","GN_SENTRY_ENV
"production","GOOGLE_API_CLIENT_ID
"881857878405-8f02t8gsk69vjs24ua6i59q7rsvnr8at.apps.googleusercontent.com","GOOGLE_MAPS_API_KEY
"AIzaSyBz-5AV-kNx9OMDQqoL7OQPyHU_eWoiFv0","GOOGLE_RECAPTCHA
{"SITE_KEY
"6Le8IVQUAAAAAHjruEj-p8IEYd_3o2x2mVvC6zAE"},"HOMEOWNERSHIP_BASE_URL
"https://www.nerdwallet.com/api/homeownership","IDENTITY
{"BASE_URL
"https://identity.east1.prod.nerdwallet.com","DATA_API_PROFILES
["global_profile","identity_email_profile","registration_tracking_profile","service_test_state_profile","subscription_profile_v3","terms_of_service_profile","user_ops_profile"],"SDK
{"DATA_API_PROFILE_CONTROLLERS
{"ENABLED
false,"PROFILES
["global_profile","identity_email_profile","registration_tracking_profile","service_test_state_profile","subscription_profile_v3","terms_of_service_profile","user_ops_profile"]},"UDP_PROFILE_SHIM
{"ENABLED
true,"PROFILES
["financial_profile","my_nerdwallet_profile","onboarding_profile"]}}},"IDENTITY_BASE_URL
"https://www.nerdwallet.com/identity","INSTAGRAM_APP_ID
1149761042224768,"INSTAGRAM_CLIENT_TOKEN
"5a5f62ae1ac48b3be495dca66c83c578","MEMBERSHIP_IN_MAINTENANCE"
false,"NWJS_ANALYTICS"
{"ENABLED"
true,"LOG_ALL_EVENTS"
false,"LOG_LEVEL"
"none"},"PRODUCTS_BASE_URL"
"https://www.nerdwallet.com/api","SEGMENT"
{"API_HOST":"siteusage.nerdwallet.com/v1","CDN_URL","https://siteusagetools.nerdwallet.com","DOMAIN"
"nerdwallet.com","JS_AUTH_TOOLS"
"ZP3f10LzTu20ayKCKLrrclFu23P2inKp","MAX_AGE"
3650,"PROTOCOL"
"https","SECURE"
true,""},"SERVICE_URLS"
{"AB"
{"DATA_API_PROFILES"
["tu_authentication_status_profile","tu_credit_report_profile","tu_personal_data_profile"]},"TUYO"
{"DATA_API_PROFILES"
["tu_authentication_status_profile","tu_credit_report_profile","tu_personal_data_profile","yodlee_account_history_profile","yodlee_profile"]},"USER_DATA_BASE_URL"
"https://www.nerdwallet.com/api","USER_MEMBER_DATA"
{"DATA_API_PROFILES"
{"WEB_PUSH_NOTIFICATIONS"}
{"DATA_API_PROFILES"}
["yodlee_account_history_profile","yodlee_profile"]},"_meta"
{"deployable"
"compass","environment"